# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da4288cd8a3f406f4537650dd9180ce66fbe010485815a4759a96914c588cd6f1059137c6c4d393301d2894746fb52206af374e24dbd9fb94e120a4113552064

test:
  secret_key_base: 6e4094c01f3271c8fa81b1d5a0fa11d47b3d16a693a923217c729c5cd402295069714fa5f3360a24d8d7ad5f5f40121ccb125e378d3a2100fbbe7dfc5d5e306d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
